### PR TITLE
Conflict with auryn

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by kelunik** [comment]
As it's a new namespace, I don't see a reason to add such a conflict rule. Where do you see a conflict?

**Comment by szepeviktor** [comment]
When a user forgets to remove auryn while upgrading.

**Comment by kelunik** [comment]
Forgetting to remove Auryn doesn't cause any issues except for an additionally installed library, but adding the conflict rule might cause issues if package A depends on `rdlowrey/auryn` and package B depends on `amphp/injector`, while this is perfectly fine and working without issues.

**Comment by szepeviktor** [comment]
Okay.

**Pull request closed without merging**
